

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]

set_property PACKAGE_PIN U20 [get_ports pattern_en]
set_property IOSTANDARD LVCMOS15 [get_ports pattern_en]



set_property PACKAGE_PIN J22 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN H22 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN J21 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN J20 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN G20 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN H20 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN H19 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN G18 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN H18 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN G17 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN H17 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN R4 [get_ports clk]
set_property PACKAGE_PIN K22 [get_ports vga_hs]
set_property PACKAGE_PIN K21 [get_ports vga_vs]

set_property IOSTANDARD LVCMOS33 [get_ports rstb]
set_property PACKAGE_PIN U7 [get_ports rstb]